cookinglog/config/routes.rb
Rails.application.routes.draw do
  get 'top/index'

  root to: 'top#index'
  # resource :top, only: :index
  match "introduction", :to => 'top#introduction',via: [:get]
  match "sweets", :to=> 'top#sweets', via: [:get]
  match "dinner", :to=> 'top#dinner', via: [:get]
  match "chinese", :to=> 'top#chinese', via: [:get]
  match "contacts", :to=> 'top#contacts', via: [:get]
  match "comments", :to=> 'top#comments', via: [:get]
end

cookinglog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cookinglog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

cookinglog/app/controllers/cooks_controller.rb
class CooksController < ApplicationController

end

cookinglog/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end

  def introduction
  end

  def sweets
  end

  def dinner
  end

  def chinese
  end

  def contacts
  end

  def comments
  end
end

cookinglog/app/helpers/application_helper.rb
module ApplicationHelper
end

cookinglog/app/helpers/top_helper.rb
module TopHelper
end

cookinglog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookinglog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="drawar">
    <%= yield %>
  </body>
</html>

cookinglog/app/views/top/chinese.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <div class="wrapper">
    <header class="header">
      <%= link_to image_tag("IMG_6578.JPG"), root_path,class: :"header__img" %>
    <span class="glyphicon glyphicon-align-right" aria-hidden="true"style="font-size: 40px"></span>
    </header>

    <nav class="nav">
      <ul class="nav_container">
        <li class="nav_container__page">
          <%= link_to "HOME", root_path, class: :"nav_container__link" %>
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
        </li>
        <li class="nav_container__page">
          <%= link_to "INTRODUCTION", introduction_path, class: :"nav_container__link" %>
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
        </li>
        <li class="nav_container__page cooks_list">
          <div class="nav_container__link" href="">COOKS</div>
          <ul class="nav_page_cooks_link">
            <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "SWEETS", sweets_path %></li>
            <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "DINNER", dinner_path %></li>
            <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "CHINESE", chinese_path %></li>
          </ul>
        </li>
        <li class="nav_container__page">
          <%= link_to "CONTACTS", contacts_path, class: :"nav_container__link" %>
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
        </li>
      </ul>
    </nav>
    <div class="page-title">
      <h3 class="page-title_text">CHINESE</h3>
    </div>
    <section class="food-list">
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>友喜屋</p>
        </div>
        <a class="food-list-img" href="">
          <img src="assets/IMG_20180106_194600.jpg" width="220" height="220" >
        </a>

      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>ラーメンヒロ</p>
        </div>
        <%= link_to image_tag("IMG_3673.JPG"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>友喜屋<br>まぜそば</p>
        </div>
        <%= link_to image_tag("IMG_6016.JPG"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>ラーメンどんき<br>担々麺</p>
        </div>
        <%= link_to image_tag("IMG_6489.JPG"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p></p>
        </div>
        <%= link_to image_tag("IMG_6351.JPG"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>魂心家</p>
        </div>
        <%= link_to image_tag("IMG_5932.JPG"), comments_path,class: :"food-list-img"%>
      </article>
    </section>
    <footer class="footer">
      <a href="">
        <img class="" src="<%= asset_path "logo_w.png" %>" alt=height="100" >
      </a>
    </footer>
  </div>
<script type="text/javascript" src="assets/top.js"></script>

cookinglog/app/views/top/comments.html.erb
<link rel="stylesheet" type="text/css" href="assets/top.css">
<div class="App">
  <div class="App-image">
    <img src="<%= asset_path "2012-12-01 14.42.02.jpg" %>" width="220" height="220" />
  </div>
  <h3 class="App-title">コメントする</h3>
  <ul class="App-list">
    <li><input type="button" value="☓">すいーとぽてと</li>
    <li><input type="button" value="☓">秋だね</li>
    <li><input type="button" value="☓">こげてる</li>
  </ul>
  <input type="text">
  <input type="button" value="追加">
</div>

cookinglog/app/views/top/contacts.html.erb
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <div class="wrapper">
      <header class="header">
        <%= link_to image_tag("IMG_6578.JPG"), root_path,class: :"header__img" %>
      <span class="glyphicon glyphicon-align-right" aria-hidden="true"style="font-size: 40px"></span>
      </header>
      <nav class="nav">
        <ul class="nav_container">
          <li class="nav_container__page">
            <%= link_to "HOME", root_path, class: :"nav_container__link" %>
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
          </li>
          <li class="nav_container__page">
            <%= link_to "INTRODUCTION", introduction_path, class: :"nav_container__link" %>
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
          </li>
          <li class="nav_container__page cooks_list">
            <a class="nav_container__link" href="">COOKS</a>
            <ul class="nav_page_cooks_link">
              <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "SWEETS", sweets_path %></li>
              <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "DINNER", dinner_path %></li>
              <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "CHINESE", chinese_path %></li>            </ul>
          </li>
          <li class="nav_container__page">
            <%= link_to "CONTACTS", contacts_path, class: :"nav_container__link" %>
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
          </li>
        </ul>
      </nav>
      <div class="page-title">
        <h3 class="page-title_text">CONTACTS</h3>
      </div>
      <section class="food-list" style="visibility:hidden">
        <article class="food-list__content">
          <a class="food-list-img" href="">
            <img width="220" height="220" >
          </a>
        </article>
        <article class="food-list__content">
          <a class="food-list-img" href="">
            <img width="220" height="220" >
          </a>
        </article>
        <article class="food-list__content">
          <a class="food-list-img" href="">
            <img width="220" height="220" >
          </a>
        </article>
        <article class="food-list__content">
          <a class="food-list-img__contacts" href="">
            <img width="220" height="220" >
          </a>
        </article>
      </section>
      <section class="contact-form">
        <p>下記の項目をご入力の上、送信ボタンを押してください。改めてお返事いたします。<br><br>＊印のある項目は入力必須となります。</p>
        <form action="">
          <dl>
            <dt>氏名＊</dt>
            <dd><input type="text"></dd>
          </dl>
          <dl>
            <dt>会社名</dt>
            <dd><input type="text"></dd>
          </dl>
          <dl>
            <dt>メールアドレス＊</dt>
            <dd><input type="text"></dd>
          </dl>
          <dl>
            <dt>お問い合わせ内容＊</dt>
            <dd><textarea name="kanso" rows="4" cols="40" style="width:100%;height:90px"></textarea></dd>
          </dl>
          <input type="submit" name="" value="送信する">
        </form>
      </section>
      <footer class="footer">
        <a href="">
          <img class="" src="<%= asset_path "logo_w.png" %>" alt=height="100" >
        </a>
      </footer>
    </div>
  <script type="text/javascript" src="assets/top.js"></script>

cookinglog/app/views/top/dinner.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <div class="wrapper">
    <header class="header">
      <%= link_to image_tag("IMG_6578.JPG"), root_path,class: :"header__img" %>
    <span class="glyphicon glyphicon-align-right" aria-hidden="true"style="font-size: 40px"></span>
    </header>

    <nav class="nav">
      <ul class="nav_container">
        <li class="nav_container__page">
          <%= link_to "HOME", root_path, class: :"nav_container__link" %>
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
        </li>
        <li class="nav_container__page">
          <%= link_to "INTRODUCTION", introduction_path, class: :"nav_container__link" %>
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
        </li>
        <li class="nav_container__page cooks_list">
          <div class="nav_container__link" href="">COOKS</div>
          <ul class="nav_page_cooks_link">
            <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "SWEETS", sweets_path %></li>
            <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "DINNER", dinner_path %></li>
            <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "CHINESE", chinese_path %></li>
          </ul>
        </li>
        <li class="nav_container__page">
          <%= link_to "CONTACTS", contacts_path, class: :"nav_container__link" %>
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
        </li>
      </ul>
    </nav>
    <div class="page-title">
      <h3 class="page-title_text">DINNER</h3>
    </div>
    <section class="food-list">
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>オムライス</p>
        </div>
        <%= link_to image_tag("IMG_4993.JPG"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>クラフトビール<br>”SVB”</p>
        </div>
        <%= link_to image_tag("IMG_6019.JPG"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>飛騨牛</p>
        </div>
        <%= link_to image_tag("IMG_3703.JPG"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>ぶたの生姜焼き</p>
        </div>
        <%= link_to image_tag("2017-01-20 18.41.13.jpg"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>ベニズワイガニ</p>
        </div>
        <%= link_to image_tag("IMG_4472.JPG"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>とり野菜味噌</p>
        </div>
        <%= link_to image_tag("IMG_4995.JPG"), comments_path,class: :"food-list-img"%>
      </article>

    </section>
    <footer class="footer">
      <a href="">
        <img class="" src="<%= asset_path "logo_w.png" %>" alt=height="100" >
      </a>
    </footer>
  </div>
<script type="text/javascript" src="assets/top.js"></script>

cookinglog/app/views/top/index.html.erb
<link rel="stylesheet" type="text/css" href="assets/top.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <div class="wrapper">
    <header class="header">
      <%= link_to image_tag("IMG_6578.JPG"), root_path,class: :"header__img" %>
    <span class="glyphicon glyphicon-align-right" aria-hidden="true"style="font-size: 40px"></span>
    </header>
    <nav class="nav">
      <ul class="nav_container">
        <li class="nav_container__page">
          <a class="nav_container__link" href="" >HOME</a>
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
        </li>
        <li class="nav_container__page">
          <%= link_to "INTRODUCTION", introduction_path, class: :"nav_container__link" %>
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
        </li>
        <li class="nav_container__page cooks_list">
          <a class="nav_container__link" href="">COOKS</a>
          <ul class="nav_page_cooks_link">
            <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "SWEETS", sweets_path %></li>
            <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "DINNER", dinner_path %></li>
            <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "CHINESE", chinese_path %></li>
          </ul>
        </li>
        <li class="nav_container__page">
          <%= link_to "CONTACTS", contacts_path, class: :"nav_container__link" %>
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
        </li>
      </ul>
    </nav>
    <section class="food-list"　style="visibility:hidden">
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>ミルフィーユ</p>
        </div>
        <%= link_to image_tag("2013-08-09 13.01.00.jpg"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>飛騨牛</p>
        </div>
        <%= link_to image_tag("IMG_3703.JPG"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>（無題）</p>
        </div>
        <%= link_to image_tag("2013-07-03 21.50.00-2.jpg"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>スイートポテト</p>
        </div>
        <%= link_to image_tag("2012-12-01 14.42.02.jpg"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>オムライス</p>
        </div>
        <%= link_to image_tag("IMG_4993.JPG"), comments_path,class: :"food-list-img"%>

      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>友喜屋</p>
        </div>
        <%= link_to image_tag("IMG_20180106_194600.jpg"), comments_path,class: :"food-list-img"%>
      </article>
    </section>
    <footer class="footer">
      <a href="">
        <img class="" src="<%= asset_path "logo_w.png" %>" alt=height="100" >
      </a>
    </footer>
  </div>
<script type="text/javascript" src="assets/top.js"></script>

cookinglog/app/views/top/introduction.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <div class="wrapper">
    <header class="header">
      <%= link_to image_tag("IMG_6578.JPG"), root_path,class: :"header__img" %>
    <span class="glyphicon glyphicon-align-right" aria-hidden="true"style="font-size: 40px"></span>
    </header>
    <nav class="nav">
      <ul class="nav_container">
        <li class="nav_container__page">
          <%= link_to "HOME", root_path, class: :"nav_container__link" %>
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
        </li>
        <li class="nav_container__page">
          <%= link_to "INTRODUCTION", introduction_path, class: :"nav_container__link" %>
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
        </li>
        <li class="nav_container__page cooks_list">
          <a class="nav_container__link" href="">COOKS</a>
          <ul class="nav_page_cooks_link">
            <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "SWEETS", sweets_path %></li>
            <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "DINNER", dinner_path %></li>
            <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "CHINESE", chinese_path %></li>
          </ul>
        </li>
        <li class="nav_container__page">
          <%= link_to "CONTACTS", contacts_path, class: :"nav_container__link" %>
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
        </li>
      </ul>
    </nav>
    <div class="page-title">
      <h3 class="page-title_text">INTRODUCTION</h3>
    </div>
    <section class="food-list" style="visibility:hidden">
      <article class="food-list__content">
        <a class="food-list-img" href="">
          <img src="" width="220" height="220" >
        </a>
      </article>
      <article class="food-list__content">
        <a class="food-list-img" href="">
          <img src="" width="220" height="220" >
        </a>
      </article>
      <article class="food-list__content">
        <a class="food-list-img" href="">
          <img src="" width="220" height="220" >
        </a>
      </article>
      <article class="food-list__content">
        <a class="food-list-img" href="">
          <img src="" width="220" height="220" >
        </a>
      </article>
      <article class="food-list__content">
        <a class="food-list-img" href="">
          <img src="" width="220" height="220" >
        </a>
      </article>
      <article class="food-list__content">
        <a class="food-list-img" href="">
          <img src="" width="220" height="220" >
        </a>
      </article>
    </section>
    <section class="introduction-text">
      <h2>About</h2>
      <p>サイト運営者が趣味で作った料理を載せるサイトです。<br><br>時折cookingしていない、運営おすすめの料理なども出てきますがご容赦ください。</p><br>
      <h2>Used</h2>
      <p>html, css, Sass, jquery, Ruby on Rails, heroku, etc...</p>
    </section>
    <footer class="footer">
      <a href="">
        <img class="" src="<%= asset_path "logo_w.png" %>" alt=height="100" >
      </a>
    </footer>
  </div>
<script type="text/javascript" src="assets/top.js"></script>

cookinglog/app/views/top/sweets.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <div class="wrapper">
    <header class="header">
      <%= link_to image_tag("IMG_6578.JPG"), root_path,class: :"header__img" %>
    <span class="glyphicon glyphicon-align-right" aria-hidden="true"style="font-size: 40px"></span>
    </header>
    <nav class="nav">
      <ul class="nav_container">
        <li class="nav_container__page">
          <%= link_to "HOME", root_path, class: :"nav_container__link" %>
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
        </li>
        <li class="nav_container__page">
          <%= link_to "INTRODUCTION", introduction_path, class: :"nav_container__link" %>
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
        </li>
        <li class="nav_container__page cooks_list">
          <div class="nav_container__link" href="">COOKS</div>
          <ul class="nav_page_cooks_link">
            <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "SWEETS", sweets_path %></li>
            <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "DINNER", dinner_path %></li>
            <li><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"style="font-size: 10px"></span><%= link_to "CHINESE", chinese_path %></li>
          </ul>
        </li>
        <li class="nav_container__page">
          <%= link_to "CONTACTS", contacts_path, class: :"nav_container__link" %>
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"style="font-size: 10px"></span>
        </li>
      </ul>
    </nav>
    <div class="page-title">
      <h3 class="page-title_text">SWEETS</h3>
    </div>
    <section class="food-list">
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>ミルフィーユ</p>
        </div>
        <%= link_to image_tag("2013-08-09 13.01.00.jpg"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>ロリポップクッキー</p>
        </div>
        <%= link_to image_tag("2013-03-01 06.37.00-2.jpg"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>（無題）</p>
        </div>
        <%= link_to image_tag("2013-07-03 21.50.00-2.jpg"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>りんごのタルト</p>
        </div>
        <%= link_to image_tag("2013-12-08 21.43.12.jpg"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>スイートポテト</p>
        </div>
        <%= link_to image_tag("2012-12-01 14.42.02.jpg"), comments_path,class: :"food-list-img"%>
      </article>
      <article class="food-list__content">
        <div class="food-list__content_title">
          <p>（無題）</p>
        </div>
        <%= link_to image_tag("2013-07-04 23.30.00.jpg"), comments_path,class: :"food-list-img"%>
      </article>
    </section>
    <footer class="footer">
      <a href="">
        <img class="" src="<%= asset_path "logo_w.png" %>" alt=height="100" >
      </a>
    </footer>
  </div>
<script type="text/javascript" src="assets/top.js"></script>